---
kind: pipeline
type: docker
name: default

clone:
    depth: 1

steps:
    -   name: deploy
        image: docker/compose:alpine-1.25.5
        volumes:
            -   name: env
                path: /drone/src/.env
            -   name: docker.sock
                path: /var/run/docker.sock
        commands:
            - docker-compose --file .swarm.yml config | docker stack deploy --prune --with-registry-auth --compose-file - sentry
        when:
            branch: [ master ]

volumes:
    -   name: docker.sock
        host:
            path: /var/run/docker.sock
    -   name: env
        host:
            path: /opt/secrets/sentry
